import { useState } from 'react';
import { Code, Copy, Check, Download, Terminal, FileCode } from 'lucide-react';
import { DownloadConfig } from '../types';

interface ScriptOutputProps {
  channelUrl: string;
  config: DownloadConfig;
  scriptType: 'bash' | 'powershell';
  setScriptType: (type: 'bash' | 'powershell') => void;
  channelId: string;
}

function generateBashScript(channelUrl: string, config: DownloadConfig, channelId: string): string {
  const channelName = channelId || 'ChannelName';
  const outputDir = `./downloads/${channelName}`;
  
  let outputTemplate = '';
  switch (config.folderStructure) {
    case 'channel/playlist/date':
      outputTemplate = `${outputDir}/%(playlist_title)s/%(upload_date>%Y-%m)s/%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s`;
      break;
    case 'channel/date':
      outputTemplate = `${outputDir}/%(upload_date>%Y)s/%(upload_date>%m)s/%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s`;
      break;
    case 'channel/playlist':
      outputTemplate = `${outputDir}/%(playlist_title)s/%(playlist_index)03d - %(title)s.%(ext)s`;
      break;
    case 'flat':
      outputTemplate = `${outputDir}/%(title)s.%(ext)s`;
      break;
  }

  const qualityMap: Record<string, string> = {
    '2160': 'bestvideo[height<=2160]+bestaudio/best[height<=2160]',
    '1440': 'bestvideo[height<=1440]+bestaudio/best[height<=1440]',
    '1080': 'bestvideo[height<=1080]+bestaudio/best[height<=1080]',
    '720': 'bestvideo[height<=720]+bestaudio/best[height<=720]',
    '480': 'bestvideo[height<=480]+bestaudio/best[height<=480]',
    'best': 'bestvideo+bestaudio/best',
  };

  const formatSelector = qualityMap[config.quality] || qualityMap['1080'];
  
  let formatExt = config.format;
  if (config.format === 'mp3' || config.format === 'm4a') {
    formatExt = config.format;
  }

  const lines: string[] = [
    '#!/bin/bash',
    '#============================================================',
    `# YouTube Channel Downloader - ${channelName}`,
    `# Generated by YT Channel Downloader`,
    `# Date: $(date +%Y-%m-%d)`,
    '#============================================================',
    '',
    '# Check if yt-dlp is installed',
    'if ! command -v yt-dlp &> /dev/null; then',
    '    echo "❌ yt-dlp is not installed. Installing..."',
    '    pip install -U yt-dlp',
    '    if ! command -v yt-dlp &> /dev/null; then',
    '        echo "❌ Failed to install yt-dlp. Please install manually:"',
    '        echo "   pip install -U yt-dlp"',
    '        exit 1',
    '    fi',
    'fi',
    '',
    '# Configuration',
    `CHANNEL_URL="${channelUrl || 'YOUR_CHANNEL_URL_HERE'}"`,
    `OUTPUT_DIR="${outputDir}"`,
    `CONCURRENT=${config.concurrentDownloads}`,
    '',
    '# Create output directory',
    'mkdir -p "$OUTPUT_DIR"',
    '',
    '#============================================================',
    '# Download all videos from channel with multi-threading',
    '#============================================================',
    '',
    'echo "🚀 Starting download..."',
    `echo "📁 Output: $OUTPUT_DIR"`,
    `echo "🧵 Threads: $CONCURRENT"`,
    `echo "📺 Quality: ${config.quality}p"`,
    `echo "📦 Format: ${config.format}"`,
    'echo "============================================================"',
    '',
    '# Main download command with all options',
    'yt-dlp \\',
    `    --format "${formatSelector}" \\`,
    `    --output "${outputTemplate}" \\`,
    `    --concurrent-fragments "$CONCURRENT" \\`,
    `    --retries ${config.retries} \\`,
    `    --retry-sleep ${config.retrySleep} \\`,
    `    --sleep-requests 1 \\`,
    `    --sleep-interval 2 \\`,
  ];

  if (config.rateLimit) {
    lines.push(`    --limit-rate "${config.rateLimit}" \\`);
  }

  if (config.format === 'mp3' || config.format === 'm4a') {
    lines.push('    --extract-audio \\');
    lines.push(`    --audio-format "${config.format}" \\`);
    lines.push('    --audio-quality 0 \\');
  } else {
    lines.push('    --merge-output-format "' + config.format + '" \\');
  }

  if (config.embedMetadata) {
    lines.push('    --embed-metadata \\');
    lines.push('    --embed-thumbnail \\');
    lines.push('    --embed-chapters \\');
  }

  if (config.downloadSubtitles) {
    const lang = config.subtitleLang || 'en';
    lines.push(`    --write-sub --write-auto-sub \\`);
    lines.push(`    --sub-lang "${lang}" \\`);
    lines.push('    --sub-format srt \\');
    lines.push('    --convert-subs srt \\');
  }

  if (config.downloadThumbnails) {
    lines.push('    --write-thumbnail \\');
    lines.push('    --convert-thumbnails jpg \\');
  }

  if (config.downloadMetadata) {
    lines.push('    --write-info-json \\');
    lines.push('    --write-description \\');
  }

  lines.push(
    '    --no-overwrites \\',
    '    --continue \\',
    '    --ignore-errors \\',
    '    --no-abort-on-error \\',
    '    --progress \\',
    '    --console-title \\',
    '    --restrict-filenames \\',
    '    --windows-filenames \\',
    '    "$CHANNEL_URL"',
    '',
    '#============================================================',
    '# Alternative: Parallel downloads using xargs (faster)',
    '# Uncomment below to use parallel mode instead',
    '#============================================================',
    '',
    '# Get all video URLs first',
    '# yt-dlp --flat-playlist --print url "$CHANNEL_URL" > /tmp/video_urls.txt',
    '',
    '# Download in parallel using xargs',
    `# cat /tmp/video_urls.txt | xargs -P $CONCURRENT -I {} yt-dlp \\`,
    `#     --format "${formatSelector}" \\`,
    `#     --output "${outputTemplate}" \\`,
    `#     --merge-output-format "${config.format}" \\`,
    '#     --embed-metadata \\',
    '#     --no-overwrites \\',
    '#     --ignore-errors \\',
    '#     {}',
    '',
    '#============================================================',
    '# Alternative: Using GNU parallel (even faster)',
    '#============================================================',
    '',
    '# yt-dlp --flat-playlist --print url "$CHANNEL_URL" | \\',
    `#     parallel -j $CONCURRENT yt-dlp \\`,
    `#         --format "${formatSelector}" \\`,
    `#         --output "${outputTemplate}" \\`,
    `#         --merge-output-format "${config.format}" \\`,
    '#         --embed-metadata \\',
    '#         --no-overwrites \\',
    '#         --ignore-errors \\',
    '#         {}',
    '',
    'echo ""',
    'echo "✅ Download complete!"',
    `echo "📂 Files saved to: $OUTPUT_DIR"`,
    '',
  );

  return lines.join('\n');
}

function generatePowerShellScript(channelUrl: string, config: DownloadConfig, channelId: string): string {
  const channelName = channelId || 'ChannelName';
  const outputDir = `.\\downloads\\${channelName}`;
  
  let outputTemplate = '';
  switch (config.folderStructure) {
    case 'channel/playlist/date':
      outputTemplate = `${outputDir}\\%(playlist_title)s\\%(upload_date>%Y-%m)s\\%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s`;
      break;
    case 'channel/date':
      outputTemplate = `${outputDir}\\%(upload_date>%Y)s\\%(upload_date>%m)s\\%(upload_date>%Y-%m-%d)s - %(title)s.%(ext)s`;
      break;
    case 'channel/playlist':
      outputTemplate = `${outputDir}\\%(playlist_title)s\\%(playlist_index)03d - %(title)s.%(ext)s`;
      break;
    case 'flat':
      outputTemplate = `${outputDir}\\%(title)s.%(ext)s`;
      break;
  }

  const qualityMap: Record<string, string> = {
    '2160': 'bestvideo[height<=2160]+bestaudio/best[height<=2160]',
    '1440': 'bestvideo[height<=1440]+bestaudio/best[height<=1440]',
    '1080': 'bestvideo[height<=1080]+bestaudio/best[height<=1080]',
    '720': 'bestvideo[height<=720]+bestaudio/best[height<=720]',
    '480': 'bestvideo[height<=480]+bestaudio/best[height<=480]',
    'best': 'bestvideo+bestaudio/best',
  };

  const formatSelector = qualityMap[config.quality] || qualityMap['1080'];

  const lines: string[] = [
    '#============================================================',
    `# YouTube Channel Downloader - ${channelName}`,
    `# Generated by YT Channel Downloader`,
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '#============================================================',
    '',
    '# Check if yt-dlp is installed',
    '$ytDlpPath = Get-Command yt-dlp -ErrorAction SilentlyContinue',
    'if (-not $ytDlpPath) {',
    '    Write-Host "❌ yt-dlp is not installed. Installing..." -ForegroundColor Yellow',
    '    pip install -U yt-dlp',
    '    $ytDlpPath = Get-Command yt-dlp -ErrorAction SilentlyContinue',
    '    if (-not $ytDlpPath) {',
    '        Write-Host "❌ Failed to install yt-dlp. Please install manually:" -ForegroundColor Red',
    '        Write-Host "   pip install -U yt-dlp" -ForegroundColor Red',
    '        exit 1',
    '    }',
    '}',
    '',
    '# Configuration',
    `$ChannelURL = "${channelUrl || 'YOUR_CHANNEL_URL_HERE'}"`,
    `$OutputDir = "${outputDir}"`,
    `$Concurrent = ${config.concurrentDownloads}`,
    '',
    '# Create output directory',
    'New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null',
    '',
    '#============================================================',
    '# Download all videos from channel with multi-threading',
    '#============================================================',
    '',
    'Write-Host "🚀 Starting download..." -ForegroundColor Green',
    'Write-Host "📁 Output: $OutputDir" -ForegroundColor Cyan',
    'Write-Host "🧵 Threads: $Concurrent" -ForegroundColor Cyan',
    `Write-Host "📺 Quality: ${config.quality}p" -ForegroundColor Cyan`,
    `Write-Host "📦 Format: ${config.format}" -ForegroundColor Cyan`,
    'Write-Host "============================================================" -ForegroundColor DarkGray',
    '',
    '# Build yt-dlp arguments',
    '$args = @(',
    `    "--format", "${formatSelector}",`,
    `    "--output", "${outputTemplate}",`,
    `    "--concurrent-fragments", "$Concurrent",`,
    `    "--retries", "${config.retries}",`,
    `    "--retry-sleep", "${config.retrySleep}",`,
    '    "--sleep-requests", "1",',
    '    "--sleep-interval", "2",',
  ];

  if (config.rateLimit) {
    lines.push(`    "--limit-rate", "${config.rateLimit}",`);
  }

  if (config.format === 'mp3' || config.format === 'm4a') {
    lines.push(
      '    "--extract-audio",',
      `    "--audio-format", "${config.format}",`,
      '    "--audio-quality", "0",',
    );
  } else {
    lines.push(`    "--merge-output-format", "${config.format}",`);
  }

  if (config.embedMetadata) {
    lines.push(
      '    "--embed-metadata",',
      '    "--embed-thumbnail",',
      '    "--embed-chapters",',
    );
  }

  if (config.downloadSubtitles) {
    const lang = config.subtitleLang || 'en';
    lines.push(
      '    "--write-sub",',
      '    "--write-auto-sub",',
      `    "--sub-lang", "${lang}",`,
      '    "--sub-format", "srt",',
      '    "--convert-subs", "srt",',
    );
  }

  if (config.downloadThumbnails) {
    lines.push(
      '    "--write-thumbnail",',
      '    "--convert-thumbnails", "jpg",',
    );
  }

  if (config.downloadMetadata) {
    lines.push(
      '    "--write-info-json",',
      '    "--write-description",',
    );
  }

  lines.push(
    '    "--no-overwrites",',
    '    "--continue",',
    '    "--ignore-errors",',
    '    "--no-abort-on-error",',
    '    "--progress",',
    '    "--restrict-filenames",',
    '    "--windows-filenames"',
    ')',
    '',
    '# Execute download',
    '& yt-dlp @args $ChannelURL',
    '',
    '#============================================================',
    '# Alternative: PowerShell parallel downloads',
    '#============================================================',
    '',
    '# Get all video URLs',
    '# $urls = yt-dlp --flat-playlist --print url $ChannelURL',
    '',
    '# Download in parallel using PowerShell jobs',
    '# $jobs = @()',
    '# foreach ($url in $urls) {',
    '#     while ((Get-Job -State Running).Count -ge $Concurrent) {',
    '#         Start-Sleep -Milliseconds 500',
    '#     }',
    '#     $jobs += Start-Job -ScriptBlock {',
    '#         param($url, $args)',
    `#         & yt-dlp @args $url`,
    '#     } -ArgumentList $url, $args',
    '# }',
    '',
    '# Wait for all jobs to complete',
    '# Get-Job | Wait-Job | Receive-Job',
    '# Remove-Job -Force $jobs',
    '',
    'Write-Host ""',
    'Write-Host "✅ Download complete!" -ForegroundColor Green',
    'Write-Host "📂 Files saved to: $OutputDir" -ForegroundColor Cyan',
    '',
  );

  return lines.join('\n');
}

export function ScriptOutput({ channelUrl, config, scriptType, setScriptType, channelId }: ScriptOutputProps) {
  const [copied, setCopied] = useState(false);

  const script = scriptType === 'bash'
    ? generateBashScript(channelUrl, config, channelId)
    : generatePowerShellScript(channelUrl, config, channelId);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(script);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const ext = scriptType === 'bash' ? 'sh' : 'ps1';
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `download_${channelId || 'channel'}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gray-900/50 backdrop-blur-sm border border-gray-800/50 rounded-2xl p-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
        <div className="flex items-center gap-2">
          <Code className="w-5 h-5 text-red-400" />
          <h2 className="text-lg font-semibold text-white">Generated Script</h2>
        </div>
        
        <div className="flex items-center gap-2">
          {/* Script type toggle */}
          <div className="flex bg-gray-800/50 rounded-lg p-0.5 border border-gray-700/50">
            <button
              onClick={() => setScriptType('bash')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                scriptType === 'bash'
                  ? 'bg-red-500/20 text-red-400 border border-red-500/30'
                  : 'text-gray-400 hover:text-gray-300 border border-transparent'
              }`}
            >
              <Terminal className="w-3.5 h-3.5" />
              Bash
            </button>
            <button
              onClick={() => setScriptType('powershell')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-sm font-medium transition-all ${
                scriptType === 'powershell'
                  ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                  : 'text-gray-400 hover:text-gray-300 border border-transparent'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" />
              PowerShell
            </button>
          </div>

          {/* Action buttons */}
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-800/50 border border-gray-700/50 rounded-lg text-sm text-gray-300 hover:text-white hover:border-gray-600 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-red-500/20 border border-red-500/30 rounded-lg text-sm text-red-400 hover:bg-red-500/30 transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            Download
          </button>
        </div>
      </div>

      {/* Script output */}
      <div className="relative">
        <div className="absolute top-3 right-3 flex items-center gap-1.5 px-2 py-1 bg-gray-800/80 rounded text-xs text-gray-400">
          <Terminal className="w-3 h-3" />
          {scriptType === 'bash' ? 'bash' : 'powershell'}
        </div>
        <pre className="bg-gray-950/80 border border-gray-800/30 rounded-xl p-4 pt-10 overflow-x-auto text-sm leading-relaxed max-h-[500px] overflow-y-auto">
          <code className="text-gray-300 font-mono whitespace-pre">
            {script.split('\n').map((line, i) => (
              <div key={i} className="hover:bg-gray-800/30 -mx-2 px-2 rounded">
                <span className="text-gray-600 select-none mr-4 inline-block w-8 text-right">
                  {i + 1}
                </span>
                <span className={
                  line.startsWith('#') ? 'text-gray-500' :
                  line.includes('--') ? 'text-blue-300' :
                  line.includes('$') ? 'text-green-300' :
                  line.includes('"') ? 'text-yellow-300' :
                  'text-gray-300'
                }>
                  {line || ' '}
                </span>
              </div>
            ))}
          </code>
        </pre>
      </div>

      {/* Instructions */}
      <div className="mt-4 p-4 bg-gray-800/30 rounded-xl border border-gray-700/30">
        <h3 className="text-sm font-medium text-white mb-2">📋 How to use:</h3>
        <ol className="text-sm text-gray-400 space-y-1 list-decimal list-inside">
          {scriptType === 'bash' ? (
            <>
              <li>Install yt-dlp: <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">pip install -U yt-dlp</code></li>
              <li>Save the script as <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">download.sh</code></li>
              <li>Make it executable: <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">chmod +x download.sh</code></li>
              <li>Run: <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">./download.sh</code></li>
            </>
          ) : (
            <>
              <li>Install yt-dlp: <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">pip install -U yt-dlp</code></li>
              <li>Save the script as <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">download.ps1</code></li>
              <li>Open PowerShell and navigate to the script location</li>
              <li>Run: <code className="text-green-400 bg-gray-900/50 px-1.5 py-0.5 rounded">.\download.ps1</code></li>
            </>
          )}
        </ol>
      </div>
    </div>
  );
}
